import { SkincareProduct, SkinProfile } from './types';

export const DEFAULT_PRODUCTS: SkincareProduct[] = [
  {
    id: '1',
    brand: 'SKIN ANGEL',
    name: 'Centella Ampoule',
    category: 'Ampoule',
    expiryDate: '2025-10',
    openDate: '2024-11-12',
    paoMonths: 12,
    remainingPercent: 75,
    imageUrl: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/KRB2eAlLOy/91akkbvi_expires_30_days.png',
    skinConcerns: ['Barrier repair', 'Soothing', 'Redness'],
    notes: 'Incredibly soothing centella extract. Helps heal the skin barrier. Feels very lightweight!',
    assignedRoutine: 'Both',
    isFavorite: true,
  },
  {
    id: '2',
    brand: 'AVOSKIN',
    name: 'Miraculous Refining Toner',
    category: 'Exfoliant',
    expiryDate: '2025-05',
    openDate: '2024-05-15',
    paoMonths: 6,
    remainingPercent: 40,
    imageUrl: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/KRB2eAlLOy/0lagtbm6_expires_30_days.png',
    skinConcerns: ['Texture', 'Exfoliation', 'Blackheads'],
    notes: 'AHA BHA PHA exfoliating toner. Use 2-3 times a week at night. Do not layer with retinol.',
    assignedRoutine: 'PM',
    isFavorite: false,
  },
  {
    id: '3',
    brand: 'LA ROCHE POSAY',
    name: 'Anthelios UVmune 400 Sunscreen',
    category: 'Sunscreen',
    expiryDate: '2026-01',
    openDate: '2024-12-01',
    paoMonths: 12,
    remainingPercent: 85,
    imageUrl: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/KRB2eAlLOy/9ve39vrm_expires_30_days.png',
    skinConcerns: ['UV Protection', 'Anti-aging'],
    notes: 'Excellent high protection sunscreen. No white cast, non-greasy, and works great under makeup.',
    assignedRoutine: 'AM',
    isFavorite: true,
  },
  {
    id: '4',
    brand: 'HADALABO',
    name: 'Gokujyun Premium Hydrating Lotion',
    category: 'Toner',
    expiryDate: '2025-11',
    openDate: '2024-10-10',
    paoMonths: 12,
    remainingPercent: 30,
    imageUrl: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/KRB2eAlLOy/l57etvqc_expires_30_days.png',
    skinConcerns: ['Hydration', 'Plumping'],
    notes: 'Super hydrating toner with 5 types of Hyaluronic acid. Put on damp skin.',
    assignedRoutine: 'Both',
    isFavorite: false,
  },
];

export const SKIN_CONCERNS_LIST = [
  'Barrier repair',
  'Soothing',
  'Redness',
  'Texture',
  'Exfoliation',
  'Blackheads',
  'Acne',
  'UV Protection',
  'Anti-aging',
  'Hydration',
  'Plumping',
  'Brightening',
  'Oil Control',
  'Pores',
];

export const CATEGORIES_LIST: { name: string; title: string; color: string }[] = [
  { name: 'Cleanser', title: 'Cleanser 🧼', color: 'bg-blue-50 text-blue-700 border-blue-200' },
  { name: 'Toner', title: 'Toner 💧', color: 'bg-sky-50 text-sky-700 border-sky-200' },
  { name: 'Ampoule', title: 'Ampoule 🧪', color: 'bg-indigo-50 text-indigo-700 border-indigo-200' },
  { name: 'Serum', title: 'Serum ✨', color: 'bg-purple-50 text-purple-700 border-purple-200' },
  { name: 'Moisturizer', title: 'Cream 🧴', color: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { name: 'Sunscreen', title: 'Sunscreen ☀️', color: 'bg-amber-50 text-amber-700 border-amber-200' },
  { name: 'Exfoliant', title: 'Exfoliant 🍋', color: 'bg-rose-50 text-rose-700 border-rose-200' },
  { name: 'Mask', title: 'Mask 🎭', color: 'bg-teal-50 text-teal-700 border-teal-200' },
  { name: 'Eye Cream', title: 'Eye Care 👀', color: 'bg-pink-50 text-pink-700 border-pink-200' },
  { name: 'Other', title: 'Other 🏷️', color: 'bg-gray-50 text-gray-700 border-gray-200' },
];

export const DEFAULT_SKIN_PROFILE: SkinProfile = {
  skinType: 'Combination',
  concerns: ['Hydration', 'Redness'],
  climate: 'Humid',
};
